### ISSUE TITLE
how can I stop log

### ISSUE THREAD

**Issue by Sophia-Gao** [ocetnik/react-native-background-timer#18]
Hi, there are too much log(eg: nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available, dumping backtrace...).It 's not convenient to debug, how can I stop log? Thanks.

**Comment by ocetnik** [comment]
Hi @Sophia-Gao,

this logs are not caused by this library. You can find how to disable them on first pages which Google offers when you paste your log there, e.g.:
 - https://forums.developer.apple.com/thread/49777
 - http://stackoverflow.com/questions/39545603/error-protocol-not-available-dumping-backtrace
 - http://stackoverflow.com/questions/39953758/facebook-ads-api-shownw-socket-set-common-sockopts-setsockopt-so-noapnfallbk-fa
 - https://my.oschina.net/wolx/blog/756339

Regards.
