### ISSUE TITLE
conflict with 'react-native-masked-text'

### ISSUE THREAD

**Issue by itcurves** [ocetnik/react-native-background-timer#21]
when I try to add your component start getting following error:

Mask type not supported.

because of this:
<TextInputMask
              style={styles.input}
              ref={'phoneText'}
              type={'us-phone'}
              placeholder='Phone Number'
              value={this.state.Phone}
              onChange={(event) => this.setState( {Phone: event.nativeEvent.text})}
               />

**Comment by ocetnik** [comment]
Hi @itcurves 

this error probably isn't caused by `react-native-background-timer` component. 

You are probably using [react-native-masked-text](https://www.npmjs.com/package/react-native-masked-text) component and there is no `us-phone` type allowed. Allowed types are listed in [docs](https://www.npmjs.com/package/react-native-masked-text#props). Maybe you should use `cel-phone` type.

Please, correct me if I'm wrong and paste here a full error log.

Thanks.

**Comment by itcurves** [comment]
Sorry it was totally my bad I wrote that component on other PC and forgot to copy that us-phone file to my new directory.

Thank you and I really appreciate your quick reply.

one thing I want to clear:
this timer component will work even phone locked correct?

**Comment by ocetnik** [comment]
Yes, this is a purpose of this component. 
If you find some error, feel free to create issue.

**Comment by itcurves** [comment]
sorry one more question. I am pretty new in RN , what if I only want to bind it for iOS not in case of android?

**Comment by ocetnik** [comment]
Sorry @itcurves, but this is really not question about this component. For questions like this you can use e.g. [stackoverflow](http://stackoverflow.com/).

Briefly, you could use it only in `index.ios.js` how [Hello World tutorial](https://facebook.github.io/react-native/docs/tutorial.html#hello-world) shows. Or you can read [documentation about Platform Specific Code](https://facebook.github.io/react-native/docs/platform-specific-code.html).
