### ISSUE TITLE
More Installation issues

### ISSUE THREAD

**Issue by fozzarelo** [ocetnik/react-native-background-timer#26]
Lexical or Preprocessor issue...

Had to remove the React/ prefixes on all your .h's and m's. 
Need to update that link. :)

**Comment by waterdoo** [comment]
+1 thanks for the fix @fozzarelo

**Comment by ocetnik** [comment]
Hi guys,

you are probably using [react-native-background-timer](https://github.com/ocetnik/react-native-background-timer) with version of React Native <0.40. From React Native version 0.40 there are some [breaking changes](https://github.com/facebook/react-native/releases/tag/v0.40.0) and one of them is, that native code on iOS must refer to headers with React namespace. This was fixed in pull request [#19](https://github.com/ocetnik/react-native-background-timer/pull/19/commits/2678602cf0ac35f7d6c4ad16eb198243e4ee44f0) and react-native-background-timer v1.0.0 was released. If you need to use react-native-background-timer with React Native version <0.40, you should have `"react-native-background-timer": "0.1.4"` in your package.json.

Please correct me if I'm wrong. Thanks.
