### ISSUE TITLE
Native module cannot be null (Jest)

### ISSUE THREAD

**Issue by SparkleFaerieCoder** [ocetnik/react-native-background-timer#72]
Just trying to import this module into my jest test: 

import BackgroundTimer from 'react-native-background-timer'

My test automatically fail, giving me this error: 

  Invariant Violation: Native module cannot be null.

      10 | import sinon from 'sinon'
      11 | import 'sinon-stub-promise'
    > 12 | import BackgroundTimer from 'react-native-background-timer'
      13 |
      14 | // import * as fetchApi from '../../../../../app/services/api'
      15 | // import Dashboard from '../../../../../app/scenes/private/index'

      at invariant (node_modules/react-native/node_modules/fbjs/lib/invariant.js:44:7)
      at new NativeEventEmitter (node_modules/react-native/Libraries/EventEmitter/NativeEventEmitter.js:31:1)
      at Object.<anonymous> (node_modules/react-native-background-timer/index.js:10:13)
      at Object.<anonymous> (__tests__/app/scenes/private/dashboard/dashboardScreen.test.js:12:33)

Anyone else run into this issue? I'm stumped.

**Comment by angelkok** [comment]
Same here, the workaround being to `require` it in the runtime block, rather than `import`:

```  let BackgroundTimer = require('react-native-background-timer').default```

The trailing `.default` was necessary. Here's what `console.log('BT: ', BackgroundTimer)` looks like without it:

```
BT:  {default: BackgroundTimer, __esModule: true}
       default: BackgroundTimer {runBackgroundTimer: ƒ, stopBackgroundTimer: ƒ, uniqueId: 0, callbacks: {…}}
       __esModule: true
       __proto__: Object
```

**Comment by dashracer** [comment]
@angelkok I've followed your code but still got the same error

**Comment by ggppwx** [comment]
Im experiencing the error on IOS, any suggestions ? thanks

**Comment by philipposslicher** [comment]
Same issue here

**Comment by parveen-lukha** [comment]
Hello, I am also facing same issue. Any solution on this.

**Comment by horaciomoreno10** [comment]
any update about of this issue?

**Comment by ocetnik** [comment]
Hi @SparkleFaerieCoder @angelkok @dashracer @ggppwx @philipposslicher @parveen-lukha @horaciomoreno10 @flacito,

if you use [create-react-native-app](https://github.com/react-community/create-react-native-app) you must [eject](https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md) it before running `react-native link`. Otherwise `react-native link` doesn't work properly. I added this info into Readme.

See also https://github.com/expo/expo/issues/56

Cheers,
David

**Comment by ocetnik** [comment]
Duplicates #70 #45

**Comment by leeferfeefer** [comment]
I solved this by having `jest.mock("react-native-background-timer",` () => {});`

**Comment by YisusMB** [comment]
i tried previously suggested solutions for this issue but no ones works for me, therefore i linking the dependency manually (in the react-native documentation) and the pod file must be added other subspecs because this dependency install react-native 0.11 (deprecated and throws errors at build phase) so my podfile is this:
``Podfile
platform :ios, '12.2'
use_frameworks!

target 'your_project_name' do
rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
pod 'SwiftyJSON', git: 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'Charts', git: 'https://github.com/danielgindi/Charts.git'
  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

end
  
post_install do |installer|
  installer.pods_project.targets.each do |target|
   target.build_configurations.each do |config|
   config.build_settings['SWIFT_VERSION'] = '5.0'
   end
  end
end
``
You must add to your workspace the RNBackgroundTimer.xcodeproj into the Libraries folder & in your project target -> build phases -> link binary with libraries -> click to add other file and select libRNBacgroundTimer.a (make sure select the ios and NOT the tvOs) and thats it it works fine

PD: If you have a problem with your project try next steps:
1` Remove the workspace file of your project ${ROOT}/ios/project.xcworkspace
2` Remove podfile.lock
3` In the prompt cd ios && pod deintegrate
4` again in the prompt pod install (inside the ios folder)

Ok i guess this may work for you guys :D

**Comment by alexfinnarn** [comment]
I don't think this is a duplicate of the other linked issues. My timer runs well in my app but not when testing via jest.

> I solved this by having jest.mock("react-native-background-timer", () => {});

As stated, that will get you past the initial error in running a Jest test. I'm not sure if I'll encounter any more issues with writing tests, but I wanted to point this out in case others read the issue and think their problem isn't with using Jest.

https://jestjs.io/docs/en/tutorial-react-native#mock-native-modules-using-jestmock
https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Jest-integration.md

Those links have more info on mocking native modules. Not sure if this module needs a mock but `react-native-community/async-storage` has an example of that in their codebase.

Hope this helps someone out in the future.
